name: Run RenovateBot

on:
  schedule:
    # https://crontab.guru/every-hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    environment:
      name: bet-renovate-bot
    container:
      image: node:18.12-buster
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Run
        run: |
          echo "Downloading Github App private key..."
          echo "${{ secrets.APP_PRIVATE_KEY }}" > app-private-key.pem
          npm run renovate
